"""
Implementation Context Engine for ArchiMate Engine

Generates AI-powered Implementation & Migration layer elements by analyzing:
- Existing technology stacks
- Business capabilities
- Platform capabilities and vendors
- Available workflow templates
- Generation pipelines

This enables one-click code generation from architecture.
"""

import json
from datetime import datetime
from typing import Dict, List, Optional, Tuple

from app import db
from app.models import (  # TechnologyStack, BusinessCapability,  # ApplicationCapability,; PlatformCapability, WorkflowTemplate, GenerationPipeline,; WorkflowPipeline,
    ArchiMateElement,
    ArchiMateRelationship,
    ArchitectureModel,
    LLMInteraction,
)
from app.services.llm_service import LLMService

from app.services.archimate.archimate_prompts import ARCHIMATE_SYSTEM_PROMPT

IMPLEMENTATION_PLANNING_PROMPT = """
You are an expert enterprise architect and implementation planner.

TASK: Generate ArchiMate 3.2 Implementation & Migration layer elements for this architecture.

ARCHITECTURE SCOPE (Application & Technology layers):
{architecture_elements}

EXISTING CONTEXT:

Technology Stacks (approved and available):
{technology_stacks}

Business Capabilities (existing):
{business_capabilities}

Application Capabilities & Vendors:
{application_capabilities}

Platform Capabilities:
{platform_capabilities}

Available Workflow Templates:
{workflow_templates}

Available Generation Pipelines:
{generation_pipelines}

CONSTRAINTS:
{constraints}

GENERATE Implementation & Migration Layer Elements:

1. **Work Packages**: Logical groups of implementation work
   - Group related deliverables
   - Consider dependencies and sequencing
   - Estimated effort in person-weeks

2. **Deliverables**: Concrete outputs (applications, services, APIs, databases, etc.)
   - Must align with Application/Technology elements above
   - Match to available technology stacks where possible
   - Consider reuse of existing capabilities

3. **Plateaus**: Stable intermediate states during migration
   - Milestone checkpoints
   - Each plateau should be functional and deployable

4. **Gaps**: Missing capabilities that need to be implemented
   - Identify what doesn't exist yet
   - What needs to be built vs bought vs integrated

5. **Implementation Events**: Key milestones and decisions
   - Go-live events
   - Approval gates
   - Major integrations

RELATIONSHIPS:
- Work Package realizes Application Component
- Work Package aggregates Deliverable
- Deliverable realizes Application Service
- Plateau aggregates Deliverable
- Implementation Event triggers Migration

WORKFLOW TEMPLATE MATCHING:
For each Work Package, recommend which Workflow Template should be used.
Consider:
- Technology stack alignment
- Platform compatibility
- Complexity match
- Generation pipeline availability

IMPORTANT:
- Prefer existing technology stacks over new ones
- Reuse existing capabilities where applicable
- Consider vendor/platform constraints
- Ensure deliverables can be generated by available pipelines
- Timeline should be realistic (provide estimates)
- Budget-conscious recommendations

Return JSON in this format:
{{
  "work_packages": [
    {{
      "name": "Work Package Name",
      "description": "What this implements",
      "deliverables": ["Deliverable 1", "Deliverable 2"],
      "effort_estimate_weeks": 8,
      "technology_stack": "Stack name from available stacks",
      "workflow_template": "Template name",
      "dependencies": ["Other WP names"],
      "realizes_elements": ["Application element names"]
    }}
  ],
  "deliverables": [
    {{
      "name": "Deliverable Name",
      "type": "Deliverable",
      "description": "What it is",
      "technology_stack": "Stack name",
      "platform": "Platform name",
      "realizes_element": "Application element name"
    }}
  ],
  "plateaus": [
    {{
      "name": "Plateau Name",
      "description": "Milestone description",
      "deliverables": ["Deliverable names"],
      "target_date": "Month X"
    }}
  ],
  "gaps": [
    {{
      "name": "Gap Name",
      "description": "What's missing",
      "impact": "high/medium/low",
      "recommendation": "How to fill the gap"
    }}
  ],
  "implementation_events": [
    {{
      "name": "Event Name",
      "description": "Event description",
      "triggers": ["What it triggers"]
    }}
  ],
  "relationships": [
    {{
      "source": "Element Name",
      "target": "Element Name",
      "type": "Realization|Aggregation|Association|Triggering"
    }}
  ],
  "metadata": {{
    "total_effort_weeks": 0,
    "estimated_duration_months": 0,
    "parallel_streams": 0,
    "critical_path": ["WP names"],
    "risks": ["Risk descriptions"]
  }}
}}
"""


class ImplementationContextEngine:
    """
    Generates Implementation & Migration layer elements with full context awareness
    """

    def __init__(self):
        """Initialize implementation context engine"""
        self.llm_service = LLMService()

    def get_context(self, architecture_id: int) -> Dict:
        """
        Gather all relevant context for implementation planning

        Args:
            architecture_id: ID of the architecture model

        Returns:
            Dictionary with all context data
        """
        context = {}

        # Get the architecture
        architecture = db.session.get(ArchitectureModel, architecture_id)
        if not architecture:
            raise ValueError(f"Architecture {architecture_id} not found")

        context["architecture"] = architecture

        # Get Application and Technology layer elements (what needs to be implemented)
        app_tech_elements = ArchiMateElement.query.filter(
            ArchiMateElement.architecture_id == architecture_id,
            ArchiMateElement.layer.in_(["application", "technology"]),
        ).all()

        context["elements_to_implement"] = [
            {
                "name": elem.name,
                "type": elem.element_type,
                "layer": elem.layer,
                "description": elem.description,
            }
            for elem in app_tech_elements
        ]

        # Get approved technology stacks
        tech_stacks = TechnologyStack.query.filter_by(is_approved=True).all()
        context["technology_stacks"] = [
            {
                "name": stack.name,
                "description": stack.description,
                "technologies": stack.technologies,
                "platform": stack.platform,
                "maturity_level": stack.maturity_level,
                "cost_rating": stack.cost_rating,
            }
            for stack in tech_stacks
        ]

        # Get business capabilities (what exists)
        capabilities = BusinessCapability.query.filter(
            BusinessCapability.maturity_level >= 3  # Established or better
        ).all()
        context["business_capabilities"] = [
            {
                "name": cap.name,
                "description": cap.description,
                "maturity_level": cap.maturity_level,
                "category": cap.category,
            }
            for cap in capabilities
        ]

        # Get application capabilities (existing vendors/systems)
        app_capabilities = ApplicationCapability.query.all()
        context["application_capabilities"] = [
            {
                "name": cap.name,
                "description": cap.description,
                "vendor": cap.vendor,
                "version": cap.version,
                "technical_debt_score": cap.technical_debt_score,
                "replacement_priority": cap.replacement_priority,
            }
            for cap in app_capabilities
        ]

        # Get platform capabilities
        platform_capabilities = PlatformCapability.query.all()
        context["platform_capabilities"] = [
            {
                "platform": cap.platform,
                "features": cap.features,
                "constraints": cap.constraints,
                "cost_model": cap.cost_model,
            }
            for cap in platform_capabilities
        ]

        # Get workflow templates
        workflow_templates = WorkflowTemplate.query.filter_by(is_active=True).all()
        context["workflow_templates"] = [
            {
                "name": template.name,
                "description": template.description,
                "category": template.category,
                "complexity": template.complexity,
                "estimated_duration": template.estimated_duration,
            }
            for template in workflow_templates
        ]

        # Get generation pipelines
        pipelines = GenerationPipeline.query.filter_by(is_active=True).all()
        context["generation_pipelines"] = [
            {
                "name": pipeline.name,
                "description": pipeline.description,
                "mode": pipeline.mode,
                "target_platform": pipeline.config.get("target_platform")
                if pipeline.config
                else None,
            }
            for pipeline in pipelines
        ]

        return context

    async def generate_implementation_layer(
        self, architecture_id: int, constraints: Optional[Dict] = None
    ) -> Tuple[Dict, LLMInteraction]:
        """
        Generate Implementation & Migration layer elements

        Args:
            architecture_id: ID of the architecture model
            constraints: Optional constraints (timeline, budget, etc.)

        Returns:
            (implementation_data, llm_interaction)
        """
        # Get context
        context = self.get_context(architecture_id)

        # Format constraints
        if not constraints:
            constraints = {
                "timeline": "6 - 12 months",
                "budget": "moderate",
                "risk_tolerance": "medium",
            }

        constraints_text = "\n".join([f"- {k}: {v}" for k, v in constraints.items()])

        # Build prompt
        prompt = IMPLEMENTATION_PLANNING_PROMPT.format(
            architecture_elements=json.dumps(context["elements_to_implement"], indent=2),
            technology_stacks=json.dumps(context["technology_stacks"], indent=2),
            business_capabilities=json.dumps(context["business_capabilities"], indent=2),
            application_capabilities=json.dumps(context["application_capabilities"], indent=2),
            platform_capabilities=json.dumps(context["platform_capabilities"], indent=2),
            workflow_templates=json.dumps(context["workflow_templates"], indent=2),
            generation_pipelines=json.dumps(context["generation_pipelines"], indent=2),
            constraints=constraints_text,
        )

        # Call LLM
        response_text, interaction = await self.llm_service.generate_with_prompt(
            prompt=prompt,
            system_prompt=ARCHIMATE_SYSTEM_PROMPT,
            model="claude - 3 - 5-sonnet - 20241022",
            max_tokens=8000,
            temperature=0.2,
        )

        # Parse JSON
        try:
            if "```json" in response_text:
                json_start = response_text.find("```json") + 7
                json_end = response_text.find("```", json_start)
                json_text = response_text[json_start:json_end].strip()
            elif "```" in response_text:
                json_start = response_text.find("```") + 3
                json_end = response_text.find("```", json_start)
                json_text = response_text[json_start:json_end].strip()
            else:
                json_text = response_text

            implementation_data = json.loads(json_text)
            return implementation_data, interaction

        except json.JSONDecodeError as e:
            raise ValueError(f"Failed to parse LLM response: {str(e)}\n\nResponse: {response_text}")

    async def create_implementation_elements(
        self, architecture_id: int, implementation_data: Dict
    ) -> Dict:
        """
        Create Implementation & Migration layer elements in database

        Args:
            architecture_id: ID of the architecture model
            implementation_data: Parsed JSON from generate_implementation_layer

        Returns:
            Summary of created elements
        """
        architecture = db.session.get(ArchitectureModel, architecture_id)
        if not architecture:
            raise ValueError(f"Architecture {architecture_id} not found")

        created = {
            "work_packages": [],
            "deliverables": [],
            "plateaus": [],
            "gaps": [],
            "implementation_events": [],
            "relationships": [],
        }

        element_map = {}  # Maps element names to IDs

        # Get existing elements (for relationship creation)
        existing_elements = {
            elem.name: elem.id
            for elem in ArchiMateElement.query.filter_by(architecture_id=architecture_id).all()
        }

        # Create Work Packages
        for wp_data in implementation_data.get("work_packages", []):
            element = ArchiMateElement(
                architecture_id=architecture_id,
                name=wp_data["name"],
                type="WorkPackage",
                layer="implementation",
                description=wp_data.get("description", ""),
                properties={
                    "effort_estimate_weeks": wp_data.get("effort_estimate_weeks", 0),
                    "technology_stack": wp_data.get("technology_stack", ""),
                    "workflow_template": wp_data.get("workflow_template", ""),
                    "dependencies": wp_data.get("dependencies", []),
                    "realizes_elements": wp_data.get("realizes_elements", []),
                },
            )
            db.session.add(element)
            db.session.flush()

            element_map[element.name] = element.id
            created["work_packages"].append(element.id)

        # Create Deliverables
        for deliv_data in implementation_data.get("deliverables", []):
            element = ArchiMateElement(
                architecture_id=architecture_id,
                name=deliv_data["name"],
                type="Deliverable",
                layer="implementation",
                description=deliv_data.get("description", ""),
                properties={
                    "technology_stack": deliv_data.get("technology_stack", ""),
                    "platform": deliv_data.get("platform", ""),
                    "realizes_element": deliv_data.get("realizes_element", ""),
                },
            )
            db.session.add(element)
            db.session.flush()

            element_map[element.name] = element.id
            created["deliverables"].append(element.id)

        # Create Plateaus
        for plateau_data in implementation_data.get("plateaus", []):
            element = ArchiMateElement(
                architecture_id=architecture_id,
                name=plateau_data["name"],
                type="Plateau",
                layer="implementation",
                description=plateau_data.get("description", ""),
                properties={
                    "deliverables": plateau_data.get("deliverables", []),
                    "target_date": plateau_data.get("target_date", ""),
                },
            )
            db.session.add(element)
            db.session.flush()

            element_map[element.name] = element.id
            created["plateaus"].append(element.id)

        # Create Gaps
        for gap_data in implementation_data.get("gaps", []):
            element = ArchiMateElement(
                architecture_id=architecture_id,
                name=gap_data["name"],
                type="Gap",
                layer="implementation",
                description=gap_data.get("description", ""),
                properties={
                    "impact": gap_data.get("impact", "medium"),
                    "recommendation": gap_data.get("recommendation", ""),
                },
            )
            db.session.add(element)
            db.session.flush()

            element_map[element.name] = element.id
            created["gaps"].append(element.id)

        # Create Implementation Events
        for event_data in implementation_data.get("implementation_events", []):
            element = ArchiMateElement(
                architecture_id=architecture_id,
                name=event_data["name"],
                type="ImplementationEvent",
                layer="implementation",
                description=event_data.get("description", ""),
                properties={"triggers": event_data.get("triggers", [])},
            )
            db.session.add(element)
            db.session.flush()

            element_map[element.name] = element.id
            created["implementation_events"].append(element.id)

        # Create Relationships
        all_element_ids = {**existing_elements, **element_map}

        for rel_data in implementation_data.get("relationships", []):
            source_name = rel_data["source"]
            target_name = rel_data["target"]

            if source_name in all_element_ids and target_name in all_element_ids:
                relationship = ArchiMateRelationship(
                    architecture_id=architecture_id,
                    source_id=all_element_ids[source_name],
                    target_id=all_element_ids[target_name],
                    type=rel_data["type"],
                    description=rel_data.get("description", ""),
                )
                db.session.add(relationship)
                db.session.flush()

                created["relationships"].append(relationship.id)

        db.session.commit()

        return created

    def match_work_packages_to_workflows(
        self, architecture_id: int, implementation_data: Dict
    ) -> List[Dict]:
        """
        Match work packages to workflow templates for code generation

        Args:
            architecture_id: ID of the architecture model
            implementation_data: Implementation data with work packages

        Returns:
            List of matches with confidence scores
        """
        matches = []

        for wp_data in implementation_data.get("work_packages", []):
            workflow_template_name = wp_data.get("workflow_template", "")

            if workflow_template_name:
                # Find the template
                template = WorkflowTemplate.query.filter_by(
                    name=workflow_template_name, is_active=True
                ).first()

                if template:
                    matches.append(
                        {
                            "work_package": wp_data["name"],
                            "workflow_template_id": template.id,
                            "workflow_template_name": template.name,
                            "confidence": "high",
                            "technology_stack": wp_data.get("technology_stack", ""),
                            "estimated_effort": wp_data.get("effort_estimate_weeks", 0),
                        }
                    )
                else:
                    matches.append(
                        {
                            "work_package": wp_data["name"],
                            "workflow_template_id": None,
                            "workflow_template_name": workflow_template_name,
                            "confidence": "low",
                            "error": "Template not found",
                            "technology_stack": wp_data.get("technology_stack", ""),
                            "estimated_effort": wp_data.get("effort_estimate_weeks", 0),
                        }
                    )

        return matches
