"""
Asset pipeline setup — Flask-Assets Environment + manifest-based fingerprinting.
"""

import json
import os

from app._bootstrap.build_info import get_build_id

# Module-level manifest cache — loaded once at startup, reloaded on each request
# in debug mode for development convenience.
_manifest_cache = {}


def _asset_version(static_folder, filename, debug=False):
    """Return a cache-busting token for a static file with no manifest entry.

    In production this is the single process-wide build identifier
    (`build_info.get_build_id()`) — the same value the `url_for` override in
    `context_processors.py` stamps on every static URL and that `/version`
    reports, so one deploy carries exactly one `?v=` value everywhere
    (ARCH-062; previously this used a per-file mtime, which is why five
    distinct stamps could be observed in a single session).

    In debug mode we keep the per-file mtime instead, so editing one asset on
    a running dev server gets a fresh URL without a restart — dev-only
    convenience, never reaching a deployed build.
    """
    if not debug:
        return get_build_id()
    if not static_folder or not filename:
        return None
    try:
        mtime = os.path.getmtime(os.path.join(static_folder, filename))
    except OSError:
        return None
    return str(int(mtime))


def _load_manifest(app):
    """Load the static asset manifest (generated by scripts/build_css.py).

    Returns a dict mapping original filenames to content-hashed filenames,
    e.g. {"css/tailwind-output.css": "css/tailwind-output.a1b2c3d4.css"}.
    """
    global _manifest_cache
    manifest_path = os.path.join(app.static_folder, "manifest.json")
    try:
        with open(manifest_path, "r", encoding="utf-8") as f:
            _manifest_cache = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        _manifest_cache = {}
    return _manifest_cache


def init_assets(app):
    """Set up Flask-Assets Environment and register bundles."""
    # --- Manifest-based asset fingerprinting (T-034) ---
    # Register the filter FIRST so it is always available even if bundle
    # setup fails (e.g. missing source files in development).
    _load_manifest(app)

    if app.debug:
        @app.before_request
        def _reload_asset_manifest():
            _load_manifest(app)

    @app.template_filter("asset_url")
    def asset_url_filter(filename):
        """Jinja2 filter: resolve a static filename through the asset manifest.

        Usage in templates:
            {{ 'css/tailwind-output.css' | asset_url }}

        Returns the URL for the content-hashed version if a manifest entry exists.
        Otherwise falls back to the original filename with an mtime-based ?v=
        cache-buster, so an asset rebuilt in place gets a fresh URL instead of
        being served forever from a stale (previously `immutable`) cache entry.
        """
        from flask import url_for
        resolved = _manifest_cache.get(filename)
        if resolved:
            # Content-hashed via the manifest → the URL already changes with the
            # bytes, so no version query is needed (and it stays cache-forever safe).
            return url_for("static", filename=resolved)
        version = _asset_version(app.static_folder, filename, debug=app.debug)
        if version:
            return url_for("static", filename=filename, v=version)
        return url_for("static", filename=filename)

    # --- Flask-Assets bundle registration (optional, non-fatal) ---
    try:
        from flask_assets import Environment

        from app.assets import app_css, app_js, vendor_css, vendor_js

        basedir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))

        assets_env = Environment(app)
        dirs = ["assets/styles", "assets/scripts"]
        for path in dirs:
            assets_env.append_path(os.path.join(basedir, "app", path))
        assets_env.url_expire = True

        if app_css:
            assets_env.register("app_css", app_css)
        if app_js:
            assets_env.register("app_js", app_js)
        if vendor_css:
            assets_env.register("vendor_css", vendor_css)
        if vendor_js:
            assets_env.register("vendor_js", vendor_js)
    except Exception as e:
        app.logger.warning(f"Flask-Assets bundle setup skipped: {e}")
