"""
Asset pipeline setup — Flask-Assets Environment + manifest-based fingerprinting.
"""

import json
import os

# Module-level manifest cache — loaded once at startup, reloaded on each request
# in debug mode for development convenience.
_manifest_cache = {}


def _load_manifest(app):
    """Load the static asset manifest (generated by scripts/build_css.py).

    Returns a dict mapping original filenames to content-hashed filenames,
    e.g. {"css/tailwind-output.css": "css/tailwind-output.a1b2c3d4.css"}.
    """
    global _manifest_cache
    manifest_path = os.path.join(app.static_folder, "manifest.json")
    try:
        with open(manifest_path, "r", encoding="utf-8") as f:
            _manifest_cache = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        _manifest_cache = {}
    return _manifest_cache


def init_assets(app):
    """Set up Flask-Assets Environment and register bundles."""
    # --- Manifest-based asset fingerprinting (T-034) ---
    # Register the filter FIRST so it is always available even if bundle
    # setup fails (e.g. missing source files in development).
    _load_manifest(app)

    if app.debug:
        @app.before_request
        def _reload_asset_manifest():
            _load_manifest(app)

    @app.template_filter("asset_url")
    def asset_url_filter(filename):
        """Jinja2 filter: resolve a static filename through the asset manifest.

        Usage in templates:
            {{ 'css/tailwind-output.css' | asset_url }}

        Returns the URL for the content-hashed version if a manifest entry exists,
        otherwise falls back to the original filename (safe for development).
        """
        from flask import url_for
        resolved = _manifest_cache.get(filename, filename)
        return url_for("static", filename=resolved)

    # --- Flask-Assets bundle registration (optional, non-fatal) ---
    try:
        from flask_assets import Environment

        from app.assets import app_css, app_js, vendor_css, vendor_js

        basedir = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))

        assets_env = Environment(app)
        dirs = ["assets/styles", "assets/scripts"]
        for path in dirs:
            assets_env.append_path(os.path.join(basedir, "app", path))
        assets_env.url_expire = True

        if app_css:
            assets_env.register("app_css", app_css)
        if app_js:
            assets_env.register("app_js", app_js)
        if vendor_css:
            assets_env.register("vendor_css", vendor_css)
        if vendor_js:
            assets_env.register("vendor_js", vendor_js)
    except Exception as e:
        app.logger.warning(f"Flask-Assets bundle setup skipped: {e}")
