"""Event log with monthly partitioning and outbox generalization.

ID: 20261002_event_log
Revises: 20261001_adr_canonical_cols
Create Date: 2026-10-02

Changes:
  1. Add entity_type, entity_id columns to transformation_outbox_events
  2. Make operation_result_id nullable (entity events have no operation result)
  3. Create event_log table partitioned by RANGE (created_at) with monthly
     child tables and per-organisation monotonic ordinal.
"""
from alembic import op
from datetime import datetime, timezone

revision = "20261002_event_log"
down_revision = "20261001_adr_canonical_cols"
branch_labels = None
depends_on = None


def upgrade():
    # 1. Generalise the outbox for entity events.
    op.execute(
        "ALTER TABLE transformation_outbox_events "
        "ADD COLUMN IF NOT EXISTS entity_type VARCHAR(80), "
        "ADD COLUMN IF NOT EXISTS entity_id INTEGER"
    )
    op.execute(
        "ALTER TABLE transformation_outbox_events "
        "ALTER COLUMN operation_result_id DROP NOT NULL"
    )

    # 2. Create the partitioned event_log.  Drop the unpartitioned one
    #    create_all() may have left behind, then build fresh.
    op.execute("DROP TABLE IF EXISTS event_log CASCADE")

    op.execute("""
        CREATE TABLE event_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            organization_id INTEGER NOT NULL,
            event_type VARCHAR(160) NOT NULL,
            event_id VARCHAR(36) NOT NULL,
            payload_json JSONB NOT NULL,
            ordinal BIGINT NOT NULL,
            entity_type VARCHAR(80),
            entity_id INTEGER,
            outbox_event_id INTEGER,
            relayed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_event_log_event_id UNIQUE (organization_id, event_id, created_at),
            CONSTRAINT ck_event_log_ordinal CHECK (ordinal >= 1)
        ) PARTITION BY RANGE (created_at)
    """)

    # 3. Create initial monthly partitions (current month + next 3 months).
    now = datetime.now(timezone.utc)
    for offset in range(4):
        month_start = datetime(now.year, now.month, 1, tzinfo=timezone.utc)
        if offset > 0:
            # Advance month
            y, m = month_start.year, month_start.month + offset
            while m > 12:
                y += 1
                m -= 12
            month_start = datetime(y, m, 1, tzinfo=timezone.utc)
        next_start = datetime(
            month_start.year + (month_start.month // 12),
            (month_start.month % 12) + 1, 1, tzinfo=timezone.utc
        )
        suffix = month_start.strftime("%Y%m")
        # Partition bounds do not support bound parameters — inline the
        # timestamp literals.
        from_literal = month_start.isoformat()
        to_literal = next_start.isoformat()
        op.execute(f"CREATE TABLE IF NOT EXISTS event_log_{suffix} "
                   f"PARTITION OF event_log "
                   f"FOR VALUES FROM ('{from_literal}'::timestamptz) "
                   f"TO ('{to_literal}'::timestamptz)")


def downgrade():
    op.execute(
        "ALTER TABLE transformation_outbox_events "
        "ALTER COLUMN operation_result_id SET NOT NULL"
    )
    op.execute(
        "ALTER TABLE transformation_outbox_events "
        "DROP COLUMN IF EXISTS entity_type, "
        "DROP COLUMN IF EXISTS entity_id"
    )
    op.execute("DROP TABLE IF EXISTS event_log CASCADE")