"""
Consulting Partners Registry

Separate from technology vendors - these are professional services firms
that provide implementation, strategy, and advisory services.
"""

CONSULTING_PARTNERS = [
    {
        "id": "accenture",
        "name": "Accenture",
        "firmType": "SYSTEM_INTEGRATOR",
        "specialization": [
            "Enterprise Architecture",
            "Digital Transformation",
            "SAP Implementation",
            "Cloud Migration",
        ],
        "apqcExpertise": ["1.0", "2.0", "8.0", "13.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "ServiceNow", "Salesforce"],
        "geographicCoverage": ["Global", "North America", "Europe", "APAC"],
        "marketPosition": "LEADER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1989,
        "headquarters": "Dublin, Ireland",
        "website": "https://www.accenture.com",
    },
    {
        "id": "deloitte",
        "name": "Deloitte",
        "firmType": "CONSULTING",
        "specialization": [
            "Business Strategy",
            "Risk Management",
            "Financial Advisory",
            "Digital Transformation",
        ],
        "apqcExpertise": ["1.0", "2.0", "9.0", "11.0", "12.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "Workday", "ServiceNow"],
        "geographicCoverage": ["Global", "North America", "Europe", "APAC", "LATAM"],
        "marketPosition": "LEADER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1845,
        "headquarters": "London, UK",
        "website": "https://www.deloitte.com",
    },
    {
        "id": "pwc",
        "name": "PwC",
        "firmType": "CONSULTING",
        "specialization": [
            "Business Strategy",
            "Risk Management",
            "Financial Advisory",
            "Digital Transformation",
        ],
        "apqcExpertise": ["1.0", "2.0", "9.0", "11.0", "12.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "Workday", "ServiceNow"],
        "geographicCoverage": ["Global", "North America", "Europe", "APAC", "LATAM"],
        "marketPosition": "LEADER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1998,
        "headquarters": "London, UK",
        "website": "https://www.pwc.com",
    },
    {
        "id": "kpmg",
        "name": "KPMG",
        "firmType": "CONSULTING",
        "specialization": [
            "Business Strategy",
            "Risk Management",
            "Financial Advisory",
            "Digital Transformation",
        ],
        "apqcExpertise": ["1.0", "2.0", "9.0", "11.0", "12.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "Workday", "ServiceNow"],
        "geographicCoverage": ["Global", "North America", "Europe", "APAC", "LATAM"],
        "marketPosition": "LEADER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1987,
        "headquarters": "Amsterdam, Netherlands",
        "website": "https://www.kpmg.com",
    },
    {
        "id": "ey",
        "name": "EY",
        "firmType": "CONSULTING",
        "specialization": [
            "Business Strategy",
            "Risk Management",
            "Financial Advisory",
            "Digital Transformation",
        ],
        "apqcExpertise": ["1.0", "2.0", "9.0", "11.0", "12.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "Workday", "ServiceNow"],
        "geographicCoverage": ["Global", "North America", "Europe", "APAC", "LATAM"],
        "marketPosition": "LEADER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1989,
        "headquarters": "London, UK",
        "website": "https://www.ey.com",
    },
    {
        "id": "capgemini",
        "name": "Capgemini",
        "firmType": "SYSTEM_INTEGRATOR",
        "specialization": [
            "Digital Transformation",
            "Cloud Services",
            "SAP Implementation",
            "AI Services",
        ],
        "apqcExpertise": ["1.0", "2.0", "8.0", "13.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "ServiceNow", "Salesforce"],
        "geographicCoverage": ["Global", "Europe", "North America", "APAC"],
        "marketPosition": "CHALLENGER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1967,
        "headquarters": "Paris, France",
        "website": "https://www.capgemini.com",
    },
    {
        "id": "atos",
        "name": "Atos",
        "firmType": "SYSTEM_INTEGRATOR",
        "specialization": [
            "Digital Transformation",
            "Cloud Services",
            "Cybersecurity",
            "SAP Implementation",
        ],
        "apqcExpertise": ["1.0", "2.0", "8.0", "11.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "ServiceNow"],
        "geographicCoverage": ["Global", "Europe", "North America", "APAC"],
        "marketPosition": "CHALLENGER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1997,
        "headquarters": "Bezons, France",
        "website": "https://www.atos.net",
    },
    {
        "id": "tcs",
        "name": "Tata Consultancy Services",
        "firmType": "SYSTEM_INTEGRATOR",
        "specialization": [
            "Digital Transformation",
            "Cloud Services",
            "SAP Implementation",
            "AI Services",
        ],
        "apqcExpertise": ["1.0", "2.0", "8.0", "13.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "ServiceNow", "Salesforce"],
        "geographicCoverage": ["Global", "APAC", "North America", "Europe"],
        "marketPosition": "LEADER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1968,
        "headquarters": "Mumbai, India",
        "website": "https://www.tcs.com",
    },
    {
        "id": "infosys",
        "name": "Infosys",
        "firmType": "SYSTEM_INTEGRATOR",
        "specialization": [
            "Digital Transformation",
            "Cloud Services",
            "SAP Implementation",
            "AI Services",
        ],
        "apqcExpertise": ["1.0", "2.0", "8.0", "13.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "ServiceNow", "Salesforce"],
        "geographicCoverage": ["Global", "APAC", "North America", "Europe"],
        "marketPosition": "LEADER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1981,
        "headquarters": "Bangalore, India",
        "website": "https://www.infosys.com",
    },
    {
        "id": "wipro",
        "name": "Wipro",
        "firmType": "SYSTEM_INTEGRATOR",
        "specialization": [
            "Digital Transformation",
            "Cloud Services",
            "SAP Implementation",
            "IT Services",
        ],
        "apqcExpertise": ["1.0", "2.0", "8.0", "13.0"],
        "vendorPartners": ["SAP", "Oracle", "Microsoft", "ServiceNow"],
        "geographicCoverage": ["Global", "APAC", "North America", "Europe"],
        "marketPosition": "CHALLENGER",
        "companySize": "ENTERPRISE",
        "foundedYear": 1945,
        "headquarters": "Bangalore, India",
        "website": "https://www.wipro.com",
    },
]

# Consulting Firm Types
CONSULTING_FIRM_TYPES = {
    "CONSULTING": "Business strategy and advisory services",
    "SYSTEM_INTEGRATOR": "Technology implementation and integration services",
    "DIGITAL_AGENCY": "Digital transformation and marketing services",
    "MANAGEMENT_CONSULTING": "Strategic management and operations consulting",
    "IT_CONSULTING": "IT strategy and technology consulting",
}

# APQC Process Expertise Mapping
APQC_CONSULTING_EXPERTISE = {
    "1.0": ["accenture", "deloitte", "pwc", "kpmg", "ey", "capgemini", "tcs", "infosys"],
    "2.0": ["accenture", "deloitte", "pwc", "kpmg", "ey", "capgemini", "tcs", "infosys"],
    "8.0": ["accenture", "capgemini", "atos", "tcs", "infosys", "wipro"],
    "9.0": ["deloitte", "pwc", "kpmg", "ey"],
    "11.0": ["accenture", "deloitte", "pwc", "kpmg", "ey", "atos"],
    "12.0": ["deloitte", "pwc", "kpmg", "ey"],
    "13.0": ["accenture", "capgemini", "tcs", "infosys"],
}
