"""
Manufacturing Domain Hierarchy Seed Data

Defines the hierarchical structure for manufacturing domains.
Primary Level 1: Production, Supply Chain, Quality, Maintenance, Engineering
Secondary Level 2: Specializations within each domain
Tertiary Level 3: Detailed sub-specializations
"""

MANUFACTURING_DOMAIN_HIERARCHY = [
    {
        "code": "PROD",
        "name": "Production",
        "description": "Production planning, execution, and control",
        "level": 1,
        "sort_order": 1,
        "domain_patterns": [
            "Production Scheduling",
            "Job Shop Planning",
            "Flow Production Control",
            "Batch Processing",
            "Lean Manufacturing",
            "Just-In-Time (JIT)",
            "Line Balancing",
        ],
        "subdomains": [
            {
                "code": "PROD-PLAN",
                "name": "Production Planning",
                "description": "Master scheduling and demand planning",
                "level": 2,
                "sort_order": 1,
                "domain_patterns": [
                    "Master Production Schedule (MPS)",
                    "Demand Forecasting",
                    "Capacity Planning",
                    "Material Requirements Planning (MRP)",
                ],
                "subdomains": [
                    {
                        "code": "PROD-PLAN-MPS",
                        "name": "Master Production Scheduling",
                        "description": "Aggregate production plans and schedule generation",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["MPS Generation", "Schedule Optimization", "Rough-Cut Capacity"],
                    },
                    {
                        "code": "PROD-PLAN-MRP",
                        "name": "Material Requirements Planning",
                        "description": "Material needs calculation and procurement triggers",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["BOM Explosion", "Net Requirements", "Planned Orders"],
                    },
                    {
                        "code": "PROD-PLAN-CAP",
                        "name": "Capacity Planning",
                        "description": "Resource and machine capacity allocation",
                        "level": 3,
                        "sort_order": 3,
                        "domain_patterns": ["CRP", "Finite Scheduling", "Resource Leveling"],
                    },
                ],
            },
            {
                "code": "PROD-EXEC",
                "name": "Production Execution",
                "description": "Shop floor execution and work order management",
                "level": 2,
                "sort_order": 2,
                "domain_patterns": [
                    "Work Order Management",
                    "Shop Floor Control",
                    "Manufacturing Execution System (MES)",
                    "Real-time Monitoring",
                ],
                "subdomains": [
                    {
                        "code": "PROD-EXEC-WO",
                        "name": "Work Order Management",
                        "description": "Work order creation, tracking, and completion",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["Work Order Lifecycle", "Routing", "Labor Tracking"],
                    },
                    {
                        "code": "PROD-EXEC-MES",
                        "name": "MES Integration",
                        "description": "Manufacturing execution system data collection",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["OEE Tracking", "Downtime Analysis", "Real-time Dashboards"],
                    },
                ],
            },
        ],
    },
    {
        "code": "SC",
        "name": "Supply Chain",
        "description": "Supply chain management and logistics",
        "level": 1,
        "sort_order": 2,
        "domain_patterns": [
            "Procurement Management",
            "Supplier Quality Management",
            "Inventory Management",
            "Logistics Optimization",
            "Supply Chain Visibility",
            "Demand-Driven Supply Networks",
            "Supplier Collaboration",
        ],
        "subdomains": [
            {
                "code": "SC-PROC",
                "name": "Procurement",
                "description": "Supplier management and purchasing",
                "level": 2,
                "sort_order": 1,
                "domain_patterns": [
                    "Vendor Management",
                    "Purchase Order Management",
                    "Supplier Scorecarding",
                    "Strategic Sourcing",
                ],
                "subdomains": [
                    {
                        "code": "SC-PROC-SRC",
                        "name": "Strategic Sourcing",
                        "description": "Supplier evaluation, selection, and contracting",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["RFQ Management", "Supplier Evaluation", "Contract Negotiation"],
                    },
                    {
                        "code": "SC-PROC-PO",
                        "name": "Purchase Order Management",
                        "description": "PO creation, approval, and receipt tracking",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["PO Lifecycle", "Goods Receipt", "Invoice Matching"],
                    },
                ],
            },
            {
                "code": "SC-INV",
                "name": "Inventory Management",
                "description": "Stock control and warehousing",
                "level": 2,
                "sort_order": 2,
                "domain_patterns": [
                    "Warehouse Management System (WMS)",
                    "ABC Analysis",
                    "Economic Order Quantity (EOQ)",
                    "Safety Stock Optimization",
                ],
                "subdomains": [
                    {
                        "code": "SC-INV-WMS",
                        "name": "Warehouse Management",
                        "description": "Warehouse operations and storage optimization",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["Bin Management", "Pick/Pack/Ship", "Cycle Counting"],
                    },
                    {
                        "code": "SC-INV-OPT",
                        "name": "Inventory Optimization",
                        "description": "Stock level optimization and replenishment",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["Safety Stock Calc", "Reorder Points", "Demand Sensing"],
                    },
                ],
            },
        ],
    },
    {
        "code": "QUAL",
        "name": "Quality",
        "description": "Quality management and assurance",
        "level": 1,
        "sort_order": 3,
        "domain_patterns": [
            "Statistical Process Control (SPC)",
            "Six Sigma",
            "Quality Control Charts",
            "Defect Detection",
            "Root Cause Analysis",
            "Corrective Action (CAPA)",
            "Quality Audits",
        ],
        "subdomains": [
            {
                "code": "QUAL-QC",
                "name": "Quality Control",
                "description": "Incoming, in-process, and final quality checks",
                "level": 2,
                "sort_order": 1,
                "domain_patterns": [
                    "Incoming Inspection",
                    "In-Process Testing",
                    "Final Quality Inspection",
                    "Sampling Plans",
                ],
                "subdomains": [
                    {
                        "code": "QUAL-QC-INC",
                        "name": "Incoming Inspection",
                        "description": "Raw material and component quality verification",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["Material Certification", "Receiving Inspection", "Supplier COA"],
                    },
                    {
                        "code": "QUAL-QC-INP",
                        "name": "In-Process Testing",
                        "description": "Quality checks during production",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["SPC Charts", "Process Monitoring", "Dimensional Checks"],
                    },
                    {
                        "code": "QUAL-QC-FIN",
                        "name": "Final Inspection",
                        "description": "Finished goods acceptance testing",
                        "level": 3,
                        "sort_order": 3,
                        "domain_patterns": ["Acceptance Testing", "Release Criteria", "Certificate of Conformance"],
                    },
                ],
            },
            {
                "code": "QUAL-QA",
                "name": "Quality Assurance",
                "description": "Quality systems and process improvement",
                "level": 2,
                "sort_order": 2,
                "domain_patterns": [
                    "ISO Compliance",
                    "Process Documentation",
                    "Continuous Improvement",
                    "Auditing Programs",
                ],
                "subdomains": [
                    {
                        "code": "QUAL-QA-ISO",
                        "name": "ISO Compliance",
                        "description": "ISO 9001/IATF 16949 management system compliance",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["ISO 9001", "IATF 16949", "Management Review"],
                    },
                    {
                        "code": "QUAL-QA-CI",
                        "name": "Continuous Improvement",
                        "description": "Kaizen and lean quality improvement programs",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["Kaizen Events", "DMAIC", "8D Problem Solving"],
                    },
                ],
            },
        ],
    },
    {
        "code": "MAINT",
        "name": "Maintenance",
        "description": "Asset maintenance and reliability",
        "level": 1,
        "sort_order": 4,
        "domain_patterns": [
            "Preventive Maintenance (PM)",
            "Predictive Maintenance (PdM)",
            "Condition Monitoring",
            "Equipment Reliability",
            "Maintenance Scheduling",
            "Mean Time Between Failures (MTBF)",
            "Total Productive Maintenance (TPM)",
        ],
        "subdomains": [
            {
                "code": "MAINT-PREV",
                "name": "Preventive Maintenance",
                "description": "Scheduled maintenance activities",
                "level": 2,
                "sort_order": 1,
                "domain_patterns": [
                    "Maintenance Scheduling",
                    "Work Order Management",
                    "Spare Parts Planning",
                    "PM Calendar Management",
                ],
                "subdomains": [
                    {
                        "code": "MAINT-PREV-SCHED",
                        "name": "PM Scheduling",
                        "description": "Calendar-based and meter-based maintenance triggers",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["Time-Based PM", "Meter-Based PM", "PM Calendar"],
                    },
                    {
                        "code": "MAINT-PREV-SPARE",
                        "name": "Spare Parts Management",
                        "description": "Critical spare parts inventory and procurement",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["Critical Spares", "Min/Max Levels", "Vendor Lead Times"],
                    },
                ],
            },
            {
                "code": "MAINT-PRED",
                "name": "Predictive Maintenance",
                "description": "Condition-based maintenance using monitoring",
                "level": 2,
                "sort_order": 2,
                "domain_patterns": [
                    "Sensor Monitoring",
                    "Vibration Analysis",
                    "Thermal Imaging",
                    "Anomaly Detection",
                ],
                "subdomains": [
                    {
                        "code": "MAINT-PRED-VIB",
                        "name": "Vibration Analysis",
                        "description": "Vibration monitoring for rotating equipment",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["FFT Analysis", "Bearing Monitoring", "Imbalance Detection"],
                    },
                    {
                        "code": "MAINT-PRED-THERM",
                        "name": "Thermal Monitoring",
                        "description": "Infrared thermography and temperature trending",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["Thermal Imaging", "Hot Spot Detection", "Temperature Trending"],
                    },
                    {
                        "code": "MAINT-PRED-ML",
                        "name": "ML-Based Prediction",
                        "description": "Machine learning models for failure prediction",
                        "level": 3,
                        "sort_order": 3,
                        "domain_patterns": ["Anomaly Detection", "RUL Estimation", "Pattern Recognition"],
                    },
                ],
            },
        ],
    },
    {
        "code": "ENG",
        "name": "Engineering",
        "description": "Product and process engineering",
        "level": 1,
        "sort_order": 5,
        "domain_patterns": [
            "Product Design",
            "Process Design",
            "CAD/CAM",
            "Simulation & Modeling",
            "Design for Manufacturing (DFM)",
            "Digital Manufacturing",
            "Industrial Engineering",
        ],
        "subdomains": [
            {
                "code": "ENG-PROD",
                "name": "Product Engineering",
                "description": "Product design and development",
                "level": 2,
                "sort_order": 1,
                "domain_patterns": [
                    "Product Design",
                    "Prototype Development",
                    "Design Validation",
                    "Bill of Materials (BOM)",
                ],
                "subdomains": [
                    {
                        "code": "ENG-PROD-CAD",
                        "name": "CAD/CAM Design",
                        "description": "Computer-aided design and manufacturing",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["3D Modeling", "Drawing Generation", "CAM Programming"],
                    },
                    {
                        "code": "ENG-PROD-BOM",
                        "name": "BOM Management",
                        "description": "Bill of materials creation and revision control",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["BOM Structure", "Engineering Change Orders", "Revision Control"],
                    },
                    {
                        "code": "ENG-PROD-SIM",
                        "name": "Simulation & Validation",
                        "description": "FEA, CFD, and design validation testing",
                        "level": 3,
                        "sort_order": 3,
                        "domain_patterns": ["FEA Analysis", "CFD Simulation", "DFMEA"],
                    },
                ],
            },
            {
                "code": "ENG-PROC",
                "name": "Process Engineering",
                "description": "Manufacturing process design",
                "level": 2,
                "sort_order": 2,
                "domain_patterns": [
                    "Process Flow Design",
                    "Line Design",
                    "Equipment Selection",
                    "Method Studies",
                ],
                "subdomains": [
                    {
                        "code": "ENG-PROC-FLOW",
                        "name": "Process Flow Design",
                        "description": "Manufacturing process sequence and flow optimization",
                        "level": 3,
                        "sort_order": 1,
                        "domain_patterns": ["Process Flow Diagrams", "Value Stream Mapping", "Cycle Time Analysis"],
                    },
                    {
                        "code": "ENG-PROC-LINE",
                        "name": "Line Design & Layout",
                        "description": "Production line configuration and factory layout",
                        "level": 3,
                        "sort_order": 2,
                        "domain_patterns": ["Layout Optimization", "Line Balancing", "Ergonomic Studies"],
                    },
                ],
            },
        ],
    },
]
