#!/usr/bin/env python
"""Task log and completion gate for the 17 Aug 2026 QA remediation register.

The register (97 active findings, compiled in ARCHIE-MASTER-Remediation-Register.md
from three source documents) is the outstanding remediation backlog. CLAUDE.md's
rule for unfinished work is to prefer a gate that COUNTS it over prose that
describes it, because a defect written down and left becomes a defect PLUS a note,
and the note reads later as a decision someone made on purpose.

So this counts it, and it counts something stricter than "somebody said done".
A finding is only closed when BOTH hold:

  * it names the commit that fixed it, and
  * it carries evidence that the fix works.

The second half exists because "fixed" and "verified" came apart twice on this
branch already: a test file was committed having never been executed (it passed
alone and failed the moment any other test ran first), and another wave wrote its
tests after the fix rather than fail-first, so they proved the code compiled rather
than that the bug was gone. A status field alone would have recorded both as done.

Evidence kinds, weakest last:
    test:<path>    an automated test that passes
    gate:<name>    a verify.py gate that mechanically prevents recurrence
    manual:<what>  human or browser verification only

Manual-only closures are counted and reported separately. They are not rejected —
some defects genuinely need eyes — but they do not survive a refactor, so the
number is worth watching rather than burying.

Usage:
    python scripts/check_qa_register.py            # what is still open, and why
    python scripts/check_qa_register.py --count    # open + unevidenced count only
    python scripts/check_qa_register.py --render   # rewrite docs/qa-remediation-log.md
"""

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
LEDGER = ROOT / "qa_findings_status.json"
LOG = ROOT / "docs" / "qa-remediation-log.md"

SEVERITY_ORDER = {"S1": 0, "S2": 1, "S3": 2, "S4": 3, "S5": 4}


def load():
    if not LEDGER.exists():
        print(f"ledger not found: {LEDGER}", file=sys.stderr)
        sys.exit(2)
    try:
        return json.loads(LEDGER.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"ledger is not valid JSON: {exc}", file=sys.stderr)
        sys.exit(2)


def classify(findings):
    """Split into (open, closed-but-unevidenced, properly closed, protect).

    `protect` is not a defect. The register lists confirmed-WORKING behaviour it
    wants kept working - the AI reasoning layer, the composer's element-reuse
    picker, ARB's aggregation and immutable decisions. Those need regression
    cover, not a fix, so they are tracked here but must not block the gate; if
    they did, the register could never close.
    """
    open_rows, unevidenced, closed, protect = [], [], [], []
    for f in findings:
        status = f.get("status")
        if status == "protect":
            protect.append(f)
        elif status != "closed":
            open_rows.append(f)
        elif not f.get("fix_commit") or not f.get("evidence"):
            unevidenced.append(f)
        else:
            closed.append(f)
    return open_rows, unevidenced, closed, protect


def _sort(rows):
    return sorted(rows, key=lambda f: (SEVERITY_ORDER.get(f.get("severity"), 9), f["id"]))


def render(data):
    """Write the owner-facing task log. Regenerated, never hand-edited."""
    findings = data["findings"]
    open_rows, unevidenced, closed, protect = classify(findings)
    manual_only = [f for f in closed
                   if all(e.startswith("manual:") for e in f["evidence"])]
    deployed = [f for f in findings if f.get("deployed")]

    out = []
    out.append("# QA remediation task log\n")
    out.append("_Generated by `scripts/check_qa_register.py --render`. "
               "Do not edit by hand — edit `qa_findings_status.json`._\n")
    out.append(f"Source: the 17 Aug 2026 QA remediation register "
               f"({len(findings)} active findings).\n")
    out.append("## Where this stands\n")
    out.append(f"| | Count |\n|---|---|")
    out.append(f"| Findings total | {len(findings)} |")
    out.append(f"| Fixed and evidenced | {len(closed)} |")
    out.append(f"| Still open | {len(open_rows)} |")
    out.append(f"| Closed but unevidenced (blocks the gate) | {len(unevidenced)} |")
    out.append(f"| Of the fixed: verified by eye only | {len(manual_only)} |")
    out.append(f"| Live in production | {len(deployed)} |\n")
    out.append("A finding counts as fixed only when its commit is recorded **and** it "
               "carries evidence. Work that is partly done stays open with a note — "
               "\"mostly done\" is open.\n")

    if unevidenced:
        out.append("## Closed without evidence — must be resolved\n")
        for f in _sort(unevidenced):
            out.append(f"- **{f['id']}** ({f['severity']}) {f.get('title','')}")
        out.append("")

    out.append("## Still open\n")
    if not open_rows:
        out.append("_Nothing outstanding._\n")
    else:
        out.append("| ID | Sev | Finding | Status |\n|---|---|---|---|")
        for f in _sort(open_rows):
            note = f.get("note") or "not started"
            out.append(f"| {f['id']} | {f['severity']} | {f.get('title','')} | {note} |")
        out.append("")

    out.append("## Fixed\n")
    out.append("| ID | Sev | Finding | Commit | Verified by | Reviewed | Deployed |\n"
               "|---|---|---|---|---|---|---|")
    for f in _sort(closed):
        ev = "; ".join(f["evidence"])
        out.append(f"| {f['id']} | {f['severity']} | {f.get('title','')} | "
                   f"`{f['fix_commit']}` | {ev} | "
                   f"{'yes' if f.get('reviewed') else 'no'} | "
                   f"{'yes' if f.get('deployed') else 'no'} |")
    out.append("")

    LOG.parent.mkdir(parents=True, exist_ok=True)
    LOG.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {LOG.relative_to(ROOT)}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", action="store_true",
                        help="print only the number of open + unevidenced findings")
    parser.add_argument("--render", action="store_true",
                        help="regenerate docs/qa-remediation-log.md")
    args = parser.parse_args()

    data = load()
    findings = data.get("findings", [])
    open_rows, unevidenced, closed, protect = classify(findings)

    if args.render:
        render(data)
        return

    blocking = len(open_rows) + len(unevidenced)
    if args.count:
        print(blocking)
        return

    if not blocking:
        print(f"QA register closed: {len(findings)}/{len(findings)} findings fixed "
              f"and evidenced.")
        return

    print(f"{blocking} of {len(findings)} QA register findings still blocking "
          f"({len(closed)} fixed and evidenced):")
    if unevidenced:
        print("\n  marked closed but carrying no commit or no evidence:")
        for f in _sort(unevidenced):
            print(f"    {f.get('severity','??'):3} {f['id']:10} {f.get('title','')}")
    if open_rows:
        print("\n  open:")
        for f in _sort(open_rows):
            note = f.get("note")
            suffix = f"  [partial: {note}]" if note else ""
            print(f"    {f.get('severity','??'):3} {f['id']:10} "
                  f"{f.get('title','')}{suffix}")


if __name__ == "__main__":
    main()
