"""
CopilotInsight — stores rule-based proactive findings for the AI Copilot.

Generated by ProactiveAnalysisService on blueprint page load (background thread).
Surfaced to architects as non-blocking banners in the blueprint completeness strip.
LLM is NOT called during insight generation — rule-based analysis only.
"""
import enum
from datetime import datetime, timedelta
from app import db


class InsightSeverity(str, enum.Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class InsightType(str, enum.Enum):
    COMPLETENESS_GAP = "completeness_gap"       # Section at 0% for > 14 days
    ARB_DEADLINE_RISK = "arb_deadline_risk"     # ARB due < 7 days, completeness < 60%
    STALE_SOLUTION = "stale_solution"           # No update in > 30 days, in_progress status
    PORTFOLIO_DUPLICATE = "portfolio_duplicate" # Similar solution name in same domain/phase
    PATTERN_AVAILABLE = "pattern_available"     # High-completeness solution shares apps/caps


class CopilotInsight(db.Model):
    __tablename__ = "copilot_insights"

    id = db.Column(db.Integer, primary_key=True)
    solution_id = db.Column(db.Integer, db.ForeignKey("solutions.id"), nullable=False, index=True)
    insight_type = db.Column(db.String(50), nullable=False)
    title = db.Column(db.String(200), nullable=False)
    body = db.Column(db.Text, nullable=False)
    suggested_query = db.Column(db.Text)
    severity = db.Column(db.String(20), default=InsightSeverity.INFO.value, nullable=False)
    seen = db.Column(db.Boolean, default=False, nullable=False)
    dismissed = db.Column(db.Boolean, default=False, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    expires_at = db.Column(db.DateTime, nullable=True)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "solution_id": self.solution_id,
            "insight_type": self.insight_type,
            "title": self.title,
            "body": self.body,
            "suggested_query": self.suggested_query,
            "severity": self.severity,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    @classmethod
    def get_unseen_for_solution(cls, solution_id: int) -> list:
        return (
            cls.query
            .filter_by(solution_id=solution_id, seen=False, dismissed=False)
            .order_by(cls.severity.desc(), cls.created_at.desc())
            .limit(5)
            .all()
        )
