from app.extensions import db

LAYER_BUSINESS = 'Business'
LAYER_APPLICATION = 'Application'
LAYER_TECHNOLOGY = 'Technology'
LAYER_CROSSCUTTING = 'CrossCutting'

SYSTEM_TEMPLATES = [
    # --- Business Layer ---
    {'name': 'User Role & Access', 'layer': LAYER_BUSINESS, 'type': 'functional',
     'default_priority': 'Must',
     'description_hint': 'Define who can perform this action and under what conditions.',
     'ac_hint': 'Given a user with role {role}, when they attempt {action}, then {expected_result}.',
     'archimate_element_type': 'BusinessRole', 'is_system': True},
    {'name': 'Business Process Support', 'layer': LAYER_BUSINESS, 'type': 'functional',
     'default_priority': 'Must',
     'description_hint': 'Describe the business process step this requirement supports.',
     'ac_hint': 'Given {trigger_event}, when {process_step} executes, then {output} is produced within {timeframe}.',
     'archimate_element_type': 'BusinessProcess', 'is_system': True},
    {'name': 'Business Rule', 'layer': LAYER_BUSINESS, 'type': 'constraint',
     'default_priority': 'Must',
     'description_hint': 'State the business rule that must be enforced by the system.',
     'ac_hint': 'Given {condition}, the system shall enforce {rule} and reject {violation} with error {message}.',
     'archimate_element_type': 'Constraint', 'is_system': True},
    {'name': 'SLA / Service Level', 'layer': LAYER_BUSINESS, 'type': 'non_functional',
     'default_priority': 'Should',
     'description_hint': 'Define the service level agreement — availability, response time, or support window.',
     'ac_hint': 'The system shall achieve {metric} of {target} measured over {period} with {exceptions}.',
     'archimate_element_type': 'Contract', 'is_system': True},
    # --- Application Layer ---
    {'name': 'User Management', 'layer': LAYER_APPLICATION, 'type': 'functional',
     'default_priority': 'Must',
     'description_hint': 'Describe user creation, update, deactivation, or authentication behaviour.',
     'ac_hint': 'Given {actor}, when {action} is performed, then the user account state changes to {state} and {notification} is sent.',
     'archimate_element_type': 'ApplicationComponent', 'is_system': True},
    {'name': 'Data Object / Entity', 'layer': LAYER_APPLICATION, 'type': 'data',
     'default_priority': 'Must',
     'description_hint': 'Define the data entity, its attributes, and lifecycle.',
     'ac_hint': 'Given a valid {entity} payload, when {endpoint} is called, then the entity is persisted with {fields} and returns {response}.',
     'archimate_element_type': 'DataObject', 'is_system': True},
    {'name': 'API / Integration', 'layer': LAYER_APPLICATION, 'type': 'integration',
     'default_priority': 'Should',
     'description_hint': 'Describe the API endpoint or system integration point.',
     'ac_hint': 'Given a {method} request to {endpoint} with {payload}, the system returns {status_code} and {response_schema} within {ms}ms.',
     'archimate_element_type': 'ApplicationInterface', 'is_system': True},
    {'name': 'Search & Query', 'layer': LAYER_APPLICATION, 'type': 'functional',
     'default_priority': 'Should',
     'description_hint': 'Define search, filter, and query behaviour including result ordering and pagination.',
     'ac_hint': 'Given {query_params}, when search is executed, then results are filtered by {criteria}, ordered by {field}, and paginated at {page_size}.',
     'archimate_element_type': 'ApplicationFunction', 'is_system': True},
    # --- Technology Layer ---
    {'name': 'Hosting & Deployment', 'layer': LAYER_TECHNOLOGY, 'type': 'infrastructure',
     'default_priority': 'Must',
     'description_hint': 'Describe where and how the system is deployed (cloud, region, container, etc.).',
     'ac_hint': 'The system shall deploy to {platform} in {region} using {deployment_method} with zero-downtime deployments.',
     'archimate_element_type': 'Node', 'is_system': True},
    {'name': 'Scalability', 'layer': LAYER_TECHNOLOGY, 'type': 'non_functional',
     'default_priority': 'Should',
     'description_hint': 'Define horizontal/vertical scaling requirements and expected peak load.',
     'ac_hint': 'The system shall handle {concurrent_users} concurrent users with {response_time}ms p95 response time and auto-scale to {max_instances} instances.',
     'archimate_element_type': 'SystemSoftware', 'is_system': True},
    {'name': 'Monitoring & Observability', 'layer': LAYER_TECHNOLOGY, 'type': 'operational',
     'default_priority': 'Should',
     'description_hint': 'Define logging, metrics, alerting, and tracing requirements.',
     'ac_hint': 'The system shall emit {metric_types} metrics, log {log_levels} events, and alert within {alert_time}s when {threshold} is exceeded.',
     'archimate_element_type': 'SystemSoftware', 'is_system': True},
    {'name': 'Backup & Recovery', 'layer': LAYER_TECHNOLOGY, 'type': 'operational',
     'default_priority': 'Must',
     'description_hint': 'Define backup frequency, retention policy, and recovery time objectives.',
     'ac_hint': 'Data shall be backed up every {frequency} with {retention} retention. RTO is {rto_hours}h and RPO is {rpo_hours}h.',
     'archimate_element_type': 'Node', 'is_system': True},
    # --- CrossCutting Layer ---
    {'name': 'Security', 'layer': LAYER_CROSSCUTTING, 'type': 'security',
     'default_priority': 'Must',
     'description_hint': 'Define authentication, authorisation, encryption, or vulnerability requirements.',
     'ac_hint': 'The system shall {security_control} using {mechanism} and reject {violation} with {response}. Verified by {test_approach}.',
     'archimate_element_type': 'Constraint', 'is_system': True},
    {'name': 'Accessibility (WCAG)', 'layer': LAYER_CROSSCUTTING, 'type': 'accessibility',
     'default_priority': 'Must',
     'description_hint': 'Define WCAG compliance level and specific accessibility requirements.',
     'ac_hint': 'The {component} shall meet WCAG {level} criteria {criterion_id}: {description}. Verified with {tool}.',
     'archimate_element_type': 'ApplicationComponent', 'is_system': True},
    {'name': 'Performance', 'layer': LAYER_CROSSCUTTING, 'type': 'non_functional',
     'default_priority': 'Should',
     'description_hint': 'Define page load times, API latency, or throughput requirements.',
     'ac_hint': 'The {operation} shall complete in under {time}ms at {percentile} percentile under {load} concurrent load.',
     'archimate_element_type': 'Constraint', 'is_system': True},
    {'name': 'Legal & Compliance', 'layer': LAYER_CROSSCUTTING, 'type': 'compliance',
     'default_priority': 'Must',
     'description_hint': 'Define regulatory, legal, or industry standard compliance requirements (GDPR, SOX, etc.).',
     'ac_hint': 'The system shall comply with {regulation} by implementing {control}. Audited via {audit_mechanism} {frequency}.',
     'archimate_element_type': 'Constraint', 'is_system': True},
    # ── Additional Business Layer templates ──
    {
        'name': 'Business Rule (Extended)',
        'layer': LAYER_BUSINESS,
        'type': 'constraint',
        'default_priority': 'Must',
        'description_hint': 'State the specific business rule or policy that must be enforced by the system.',
        'ac_hint': 'Given {situation}, when {trigger_event}, then the system shall enforce {rule} and {outcome}.',
        'archimate_element_type': 'BusinessRule',
        'is_system': True,
    },
    {
        'name': 'Service Level Agreement',
        'layer': LAYER_BUSINESS,
        'type': 'non_functional',
        'default_priority': 'Must',
        'description_hint': 'Define the SLA commitment: availability, response time, support tier, and penalties.',
        'ac_hint': 'The system shall achieve {metric} of {target_value} measured over {time_period}, with {penalty} if breached.',
        'archimate_element_type': 'Contract',
        'is_system': True,
    },
    {
        'name': 'Stakeholder Role Definition',
        'layer': LAYER_BUSINESS,
        'type': 'functional',
        'default_priority': 'Should',
        'description_hint': 'Define the role, responsibilities, and permissions of a stakeholder in the system.',
        'ac_hint': 'Given a user with role {role_name}, they shall be able to {permitted_actions} but not {restricted_actions}.',
        'archimate_element_type': 'BusinessActor',
        'is_system': True,
    },
    {
        'name': 'Regulatory Compliance',
        'layer': LAYER_BUSINESS,
        'type': 'compliance',
        'default_priority': 'Must',
        'description_hint': 'Specify which regulatory standard must be met and what evidence is required.',
        'ac_hint': 'The system shall comply with {regulation} by implementing {control} as verified by {audit_evidence}.',
        'archimate_element_type': 'Driver',
        'is_system': True,
    },
    # ── Additional Application Layer templates ──
    {
        'name': 'API Endpoint',
        'layer': LAYER_APPLICATION,
        'type': 'functional',
        'default_priority': 'Must',
        'description_hint': 'Define the REST/GraphQL endpoint: method, path, request/response schema, and auth requirements.',
        'ac_hint': 'Given an authenticated {role} calls {METHOD} {/path} with {request_body}, then the system returns {HTTP_status} with {response_schema}.',
        'archimate_element_type': 'ApplicationInterface',
        'is_system': True,
    },
    {
        'name': 'User Authentication',
        'layer': LAYER_APPLICATION,
        'type': 'functional',
        'default_priority': 'Must',
        'description_hint': 'Describe the authentication mechanism: SSO, MFA, token type, and session management.',
        'ac_hint': 'Given {credential_type}, when the user authenticates, then a {token_type} valid for {duration} is issued and {session_policy} applies.',
        'archimate_element_type': 'ApplicationComponent',
        'is_system': True,
    },
    {
        'name': 'Data Validation',
        'layer': LAYER_APPLICATION,
        'type': 'functional',
        'default_priority': 'Must',
        'description_hint': 'Specify what data is validated, the rules applied, and the error feedback mechanism.',
        'ac_hint': 'When {field_name} receives {invalid_input}, the system displays {error_message} and does not persist the record.',
        'archimate_element_type': 'DataObject',
        'is_system': True,
    },
    {
        'name': 'Search and Filter',
        'layer': LAYER_APPLICATION,
        'type': 'functional',
        'default_priority': 'Should',
        'description_hint': 'Define searchable fields, filter options, pagination, and result ranking.',
        'ac_hint': 'Given {search_term} entered, the system returns up to {max_results} results within {response_time_ms}ms ranked by {ranking_criteria}.',
        'archimate_element_type': 'ApplicationService',
        'is_system': True,
    },
    {
        'name': 'Notification and Alerting',
        'layer': LAYER_APPLICATION,
        'type': 'functional',
        'default_priority': 'Should',
        'description_hint': 'Specify what events trigger notifications, delivery channels, and user preferences.',
        'ac_hint': 'When {event} occurs, the system notifies {recipient} via {channel} within {sla_time} including {required_content}.',
        'archimate_element_type': 'ApplicationEvent',
        'is_system': True,
    },
    {
        'name': 'Bulk Import / Export',
        'layer': LAYER_APPLICATION,
        'type': 'functional',
        'default_priority': 'Could',
        'description_hint': 'Define file formats, size limits, validation rules, and progress feedback for bulk operations.',
        'ac_hint': 'Given a {format} file with up to {max_records} records, the import completes within {time_limit}s with {error_handling} for invalid rows.',
        'archimate_element_type': 'DataObject',
        'is_system': True,
    },
    {
        'name': 'Workflow Automation',
        'layer': LAYER_APPLICATION,
        'type': 'functional',
        'default_priority': 'Should',
        'description_hint': 'Describe the workflow steps, triggers, decision points, and automation rules.',
        'ac_hint': 'When {trigger_condition}, the workflow progresses from {state_from} to {state_to} and notifies {stakeholder}.',
        'archimate_element_type': 'ApplicationProcess',
        'is_system': True,
    },
    {
        'name': 'Audit Log',
        'layer': LAYER_APPLICATION,
        'type': 'compliance',
        'default_priority': 'Must',
        'description_hint': 'Specify what actions are logged, retention period, tamper-evidence, and access controls for audit logs.',
        'ac_hint': 'All {action_types} performed by users are logged with {log_fields} and retained for {retention_period}.',
        'archimate_element_type': 'DataObject',
        'is_system': True,
    },
    # ── Technology Layer templates ──
    {
        'name': 'Cloud Hosting',
        'layer': LAYER_TECHNOLOGY,
        'type': 'operational',
        'default_priority': 'Must',
        'description_hint': 'Specify cloud provider, regions, service tier, and deployment topology.',
        'ac_hint': 'The application is deployed on {cloud_provider} in {regions} using {service_tier} with {redundancy_level} redundancy.',
        'archimate_element_type': 'Node',
        'is_system': True,
    },
    {
        'name': 'Scalability Requirements',
        'layer': LAYER_TECHNOLOGY,
        'type': 'non_functional',
        'default_priority': 'Must',
        'description_hint': 'Define horizontal/vertical scaling strategy, auto-scaling triggers, and capacity limits.',
        'ac_hint': 'The system shall scale to handle {peak_concurrent_users} users with {max_latency_ms}ms P95 latency using {scaling_strategy}.',
        'archimate_element_type': 'SystemSoftware',
        'is_system': True,
    },
    {
        'name': 'Disaster Recovery',
        'layer': LAYER_TECHNOLOGY,
        'type': 'operational',
        'default_priority': 'Must',
        'description_hint': 'Define RPO, RTO, backup strategy, and recovery procedure.',
        'ac_hint': 'The system achieves RPO of {rpo} and RTO of {rto} using {backup_strategy} with {test_frequency} DR tests.',
        'archimate_element_type': 'Node',
        'is_system': True,
    },
    {
        'name': 'Monitoring and Observability',
        'layer': LAYER_TECHNOLOGY,
        'type': 'operational',
        'default_priority': 'Should',
        'description_hint': 'Specify metrics, log aggregation, tracing, alerting thresholds, and dashboards.',
        'ac_hint': 'The system exposes {metric_types} metrics via {monitoring_tool} with alerts when {alert_condition} for {alert_duration}.',
        'archimate_element_type': 'SystemSoftware',
        'is_system': True,
    },
    {
        'name': 'Network Security',
        'layer': LAYER_TECHNOLOGY,
        'type': 'non_functional',
        'default_priority': 'Must',
        'description_hint': 'Define firewall rules, WAF configuration, DDoS protection, and network segmentation.',
        'ac_hint': 'All traffic is {encryption_protocol} encrypted; {firewall_rules} are enforced; WAF blocks {attack_types}.',
        'archimate_element_type': 'CommunicationNetwork',
        'is_system': True,
    },
    {
        'name': 'Container Orchestration',
        'layer': LAYER_TECHNOLOGY,
        'type': 'operational',
        'default_priority': 'Should',
        'description_hint': 'Specify container platform (Kubernetes/ECS), resource limits, health checks, and rolling update strategy.',
        'ac_hint': 'Services run as {container_runtime} containers with {cpu_limit}/{memory_limit} limits, liveness probes at {probe_path}, and rolling updates with {max_surge} surge.',
        'archimate_element_type': 'SystemSoftware',
        'is_system': True,
    },
    # ── Cross-Cutting / Non-Functional templates ──
    {
        'name': 'Performance Benchmark',
        'layer': LAYER_CROSSCUTTING,
        'type': 'non_functional',
        'default_priority': 'Must',
        'description_hint': 'Specify performance targets: throughput, latency percentiles, and test conditions.',
        'ac_hint': 'Under {load_condition}, the system processes {throughput} requests/second with P50 {p50_ms}ms, P95 {p95_ms}ms, P99 {p99_ms}ms.',
        'archimate_element_type': 'BusinessObject',
        'is_system': True,
    },
    {
        'name': 'Accessibility WCAG Extended',
        'layer': LAYER_CROSSCUTTING,
        'type': 'compliance',
        'default_priority': 'Must',
        'description_hint': 'Specify the WCAG conformance level, assistive technologies supported, and testing approach.',
        'ac_hint': 'The {component} meets WCAG {version} {level} as verified by {tool} with zero {severity} violations.',
        'archimate_element_type': 'ApplicationComponent',
        'is_system': True,
    },
    {
        'name': 'Data Privacy',
        'layer': LAYER_CROSSCUTTING,
        'type': 'compliance',
        'default_priority': 'Must',
        'description_hint': 'Specify what PII is collected, purpose limitation, consent mechanism, and data subject rights.',
        'ac_hint': 'The system collects only {pii_fields} with {consent_mechanism}; users can exercise {rights} within {response_sla}.',
        'archimate_element_type': 'BusinessObject',
        'is_system': True,
    },
    {
        'name': 'Internationalisation (i18n)',
        'layer': LAYER_CROSSCUTTING,
        'type': 'functional',
        'default_priority': 'Could',
        'description_hint': 'Define supported locales, translation mechanism, date/currency formats, and RTL support.',
        'ac_hint': 'The UI displays in {locale_list} with all strings translated via {translation_mechanism} and correct {date_currency_format} formatting.',
        'archimate_element_type': 'ApplicationComponent',
        'is_system': True,
    },
    {
        'name': 'Error Handling and Recovery',
        'layer': LAYER_CROSSCUTTING,
        'type': 'non_functional',
        'default_priority': 'Must',
        'description_hint': 'Specify how errors are surfaced to users, logged, and recovered from.',
        'ac_hint': 'When {error_type} occurs, the system displays {user_message}, logs {error_details} at {log_level}, and retries {retry_policy}.',
        'archimate_element_type': 'ApplicationComponent',
        'is_system': True,
    },
    {
        'name': 'Dependency and Third-Party Risk',
        'layer': LAYER_CROSSCUTTING,
        'type': 'constraint',
        'default_priority': 'Should',
        'description_hint': 'Document external dependencies, licensing constraints, vendor risk, and fallback strategies.',
        'ac_hint': 'The dependency {dependency_name} version {version_range} with {license_type} is approved; fallback is {fallback_strategy}.',
        'archimate_element_type': 'BusinessObject',
        'is_system': True,
    },
    {
        'name': 'Cost and Budget Constraint',
        'layer': LAYER_CROSSCUTTING,
        'type': 'constraint',
        'default_priority': 'Must',
        'description_hint': 'Define budget ceiling, cost allocation, and cost monitoring requirements.',
        'ac_hint': 'Monthly infrastructure cost shall not exceed {budget_ceiling} as monitored by {cost_tool} with alerts at {threshold_percent}% of budget.',
        'archimate_element_type': 'Driver',
        'is_system': True,
    },
    {
        'name': 'Mobile Responsiveness',
        'layer': LAYER_CROSSCUTTING,
        'type': 'non_functional',
        'default_priority': 'Should',
        'description_hint': 'Specify target device categories, breakpoints, and touch interaction requirements.',
        'ac_hint': 'The {page_component} renders correctly on {device_categories} at breakpoints {breakpoints} with touch targets >= {min_size_px}px.',
        'archimate_element_type': 'ApplicationComponent',
        'is_system': True,
    },
]


class RequirementTemplate(db.Model):
    __tablename__ = 'requirement_template'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    layer = db.Column(db.String(30), nullable=False)   # Business/Application/Technology/CrossCutting
    type = db.Column(db.String(30), nullable=True)
    default_priority = db.Column(db.String(10), nullable=True)
    description_hint = db.Column(db.Text, nullable=True)
    ac_hint = db.Column(db.Text, nullable=True)
    archimate_element_type = db.Column(db.String(60), nullable=True)
    is_system = db.Column(db.Boolean, nullable=False, default=True)

    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'layer': self.layer,
            'type': self.type,
            'default_priority': self.default_priority,
            'description_hint': self.description_hint,
            'ac_hint': self.ac_hint,
            'archimate_element_type': self.archimate_element_type,
            'is_system': self.is_system,
        }
